# Generated by Django 4.2.7 on 2023-12-01 19:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CoffeeShop",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                ("address", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Review",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("review_text", models.TextField()),
                ("rating", models.PositiveIntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "coffee_shop_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="coffeeshop.coffeeshop",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CoffeeShopImage",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("picture", models.ImageField(upload_to="coffeeshop_pictures/")),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "coffee_shop_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="coffeeshop.coffeeshop",
                    ),
                ),
            ],
        ),
    ]
